import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("", inter.className)}>
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
            <Sidebar/>
            <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
                <Header/>
                {children}
            </div>
        </div>
      </body>
    </html>
  );
}
